### ISSUE TITLE
Increase inventory API rate limit

### ISSUE THREAD

**Issue by jawrainey** [ideafast/stack#9]
> There is an API rate limit on the inventory of [150 requests by default](https://snipe-it.readme.io/reference#api-throttling). Critically, once the rate limit is met calls to the inventory's database appear to be disabled for a set period (about a minute) that would impact anyone using the inventory website.
>
> We should increase this to a more reasonable limit, e.g., 3x current limit (450)? This requires modifying the source code within the docker container as there appears to yet be no way to do this via an `.env`. 

-- Jay@[middleware-API](https://github.com/ideafast/middleware-services/pull/42/files#r575304224)

**Comment by davidverweij** [comment]
Pulling in the discussion at the middleware repo, with thoughts on
- [caching serial lookups](https://github.com/ideafast/middleware-services/pull/42#discussion_r575304224), and
- [querying all devices at the beginning of a DAG](https://github.com/ideafast/middleware-services/pull/42#discussion_r577032306)

**Comment by jawrainey** [comment]
Closed as resolved [here](https://github.com/ideafast/middleware-services/pull/63)
